name: Setup Workers
runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - name: Setup pnpm (corepack)
      shell: bash
      run: |
        corepack enable
        corepack prepare pnpm@9.12.3 --activate
    - name: Install workers dependencies
      shell: bash
      run: pnpm --filter ./workers install --frozen-lockfile
